version: "2"
services:
  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    labels:
      - traefik.port=8080
      - "traefik.frontend.rule=Host:proxy.docker.local;AddPrefix:/dashboard/;"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
    expose:
      - 8080
    networks:
      - proxy
networks:
  proxy:
    external: true
