version: '2'
services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    restart: unless-stopped
    expose:
      - 80
      - 443
      - 22
    labels:
      - traefik.port=80
      - traefik.protocol=http
      - traefik.frontend.rule=Host:git.docker.local
    volumes:
     - ./gitlab/config:/etc/gitlab
     - ./gitlab/logs:/var/log/gitlab
     - ./gitlab/data:/var/opt/gitlab
    networks:
      - proxy

networks:
  proxy:
    external: true
