version: '2'
services:
  poste:
    container_name: poste
    image: analogic/poste.io
    restart: unless-stopped
    ports:
      - 25:25
      - 110:110
      - 143:143
      - 465:465
      - 587:587
      - 993:993
      - 995:995
    expose:
      - 80/tcp
      - 443/tcp
    environment:
      - HTTPS=OFF
    networks:
      - proxy
    labels:
      - traefik.port=80
      - traefik.protocol=http
      - traefik.frontend.headers.SSLRedirect=false
      - traefik.frontend.rule=Host:post.docker.local
    volumes:
      - ./poste/data:/data
      - /etc/localtime:/etc/localtime:ro
networks:
  proxy:
     external: true
